[package]
name = "dbe"
version = "0.1.0"
edition = "2024"

[dependencies]
pyo3 = { version = "0.28.2", features = ["extension-module"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[lib]
name = "_core"
crate-type = ["cdylib"]

[[bench]]
name = "pv_bench"
harness = false
