from collections.abc import Callable

class Preference:
    def __init__(
        self,
        utility_func: Callable[[list[float]], float],
        min_bounds: list[float],
        max_bounds: list[float],
        *,
        validate: bool = True,
    ) -> None: ...
    def get_utility(self, bundle: list[float]) -> float: ...
    def get_mu(self, bundle: list[float], good: int) -> float: ...
    def get_mrs(self, bundle: list[float], good_i: int, good_j: int) -> float: ...

class Config:
    class Preference:
        @classmethod
        def set(cls, **kwargs: object) -> type["Config.Preference"]: ...
        @classmethod
        def state(cls) -> dict[str, object]: ...
        @classmethod
        def restore_defaults(cls) -> type["Config.Preference"]: ...

    class Indifference:
        @classmethod
        def set(cls, **kwargs: object) -> type["Config.Indifference"]: ...
        @classmethod
        def state(cls) -> dict[str, object]: ...
        @classmethod
        def restore_defaults(cls) -> type["Config.Indifference"]: ...

    class Optimisation:
        @classmethod
        def set(cls, **kwargs: object) -> type["Config.Optimisation"]: ...
        @classmethod
        def state(cls) -> dict[str, object]: ...
        @classmethod
        def restore_defaults(cls) -> type["Config.Optimisation"]: ...

    @classmethod
    def set(cls, **kwargs: object) -> type["Config"]: ...
    @classmethod
    def state(cls) -> dict[str, object]: ...
    @classmethod
    def defaults(cls) -> dict[str, object]: ...
    @classmethod
    def restore_defaults(cls) -> type["Config"]: ...

def optimal_bundle(
    pref: Preference,
    prices: list[float],
    income: float,
    **kwargs: object,
) -> list[float]: ...
def trace_indifference_curve(
    pref: Preference,
    target_utility: float,
    good_i: int,
    good_j: int,
    *,
    n_points: int | None = None,
    tol: float | None = None,
) -> list[tuple[float, float]]: ...
def get_standard_config() -> dict[str, object]: ...
def set_standard_config(
    *,
    preference: dict[str, object] | None = None,
    indifference: dict[str, object] | None = None,
    optimisation: dict[str, object] | None = None,
) -> None: ...
def restore_standard_config() -> None: ...
