[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "dbe"
version = "0.1.0"
description = "Collection of basic economic functionalities."
requires-python = ">=3.13"

[tool.maturin]
python-source = "src"
module-name = "dbe._core"
features = ["pyo3/extension-module"]
manifest-path = "../crates/dbe-python/Cargo.toml"

[tool.pytest]
testpaths = ["tests"]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
